# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'todoSlayer' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for todoSlayer
    pod 'SnapKit', '~> 5.0.0'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
    pod 'FSCalendar'
    
end
